/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGUI;

import java.awt.Color;

/**
 *
 * @author Lenovo
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSeccion
     */
    public IniciarSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Usuariotxt = new javax.swing.JTextField();
        Contraseña = new javax.swing.JLabel();
        Contraseñatxt = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        BotonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/istockphoto-838208680-612x612.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 290, 510));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setText("INICIAR SESION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 230, 30));

        Usuario.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Usuario.setText("NOMBRE DE USUARIO: ");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        Usuariotxt.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Usuariotxt.setForeground(new java.awt.Color(204, 204, 204));
        Usuariotxt.setBorder(null);
        Usuariotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuariotxtMousePressed(evt);
            }
        });
        Usuariotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariotxtActionPerformed(evt);
            }
        });
        jPanel1.add(Usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, 30));

        Contraseña.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Contraseña.setText("CONTRASEÑA: ");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        Contraseñatxt.setForeground(new java.awt.Color(204, 204, 204));
        Contraseñatxt.setBorder(null);
        Contraseñatxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContraseñatxtMousePressed(evt);
            }
        });
        Contraseñatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñatxtActionPerformed(evt);
            }
        });
        jPanel1.add(Contraseñatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 270, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 233, 240, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 270, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 10));

        BotonEntrar.setBackground(new java.awt.Color(102, 102, 255));
        BotonEntrar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        BotonEntrar.setText("ENTRAR");
        BotonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonEntrarMouseExited(evt);
            }
        });
        jPanel1.add(BotonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariotxtActionPerformed

    private void ContraseñatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñatxtActionPerformed

    private void UsuariotxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariotxtMousePressed
        if(Usuariotxt.getText().equals("Ingrese su nombre de Usuario")){
            Usuariotxt.setText("");
            Usuariotxt.setForeground(Color.black);
        }
        if(String.valueOf(Contraseñatxt.getPassword()).isEmpty()){
            Contraseñatxt.setText("********");
            Contraseñatxt.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_UsuariotxtMousePressed

    private void ContraseñatxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñatxtMousePressed
        if(String.valueOf(Contraseñatxt.getPassword()).equals("********")){
            Contraseñatxt.setText("");
            Contraseñatxt.setForeground(Color.BLACK);
        }
        if(Usuariotxt.getText().isEmpty()){
            Usuariotxt.setText("Ingrese su nombre de Usuario");
            Usuariotxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ContraseñatxtMousePressed

    private void BotonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEntrarMouseEntered
        BotonEntrar.setBackground(new Color(200, 242, 255));
    }//GEN-LAST:event_BotonEntrarMouseEntered

    private void BotonEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEntrarMouseExited
        BotonEntrar.setBackground(new Color(51, 102, 255));
    }//GEN-LAST:event_BotonEntrarMouseExited

    private void BotonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEntrarMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario ingresado correctamente.\n\nUsuario: " + Usuariotxt.getText() + "\nContraseña: " + String.valueOf(Contraseñatxt.getPassword()));
        this.setVisible(false);
        Opcion op = new Opcion();
        op.setVisible(true);
    }//GEN-LAST:event_BotonEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrar;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JPasswordField Contraseñatxt;
    private javax.swing.JLabel Usuario;
    private javax.swing.JTextField Usuariotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
